#!/bin/sh
# Regenerate the derived files of the relay kit from their sources:
#   cloud-init.yaml   embeds setup.sh and the host files, each gzip-compressed
#                     and base64-encoded (cloud-init "encoding: gz+b64"): as
#                     plain text the kit exceeds Hetzner's 32 KiB user data
#   fly/config.toml   copy of config.toml; the Fly build context is fly/ only
# Usage:
#   sh render.sh           rewrite both files
#   sh render.sh --check   exit 1 if either is stale. It decodes every
#                          embedded file and compares it with its source, so
#                          another gzip build does not count as drift. It also
#                          fails if fly/entrypoint.sh's default RUST_LOG differs
#                          from iroh-relay.service's, which "What is logged"
#                          in README.md relies on for both variants.
# Edit the sources and re-render; never edit the derived files by hand.
set -eu
cd "$(dirname -- "$0")"

# kit file : destination on the host : mode
FILES='setup.sh:/opt/oxfer-relay/setup.sh:0755
config.toml:/opt/oxfer-relay/config.toml:0644
iroh-relay.service:/opt/oxfer-relay/iroh-relay.service:0644
nftables.conf:/opt/oxfer-relay/nftables.conf:0644
journald-oxfer-relay.conf:/opt/oxfer-relay/journald-oxfer-relay.conf:0644
sshd-oxfer-relay.conf:/opt/oxfer-relay/sshd-oxfer-relay.conf:0644
unattended-upgrades.conf:/opt/oxfer-relay/unattended-upgrades.conf:0644
logrotate-oxfer-relay.conf:/opt/oxfer-relay/logrotate-oxfer-relay.conf:0644
tmpfiles-oxfer-relay.conf:/opt/oxfer-relay/tmpfiles-oxfer-relay.conf:0644
oxfer-relay-ban:/opt/oxfer-relay/oxfer-relay-ban:0755
oxfer-relay-ban.service:/opt/oxfer-relay/oxfer-relay-ban.service:0644
oxfer-relay-ban.timer:/opt/oxfer-relay/oxfer-relay-ban.timer:0644'

render_cloud_init() {
	cat <<'EOF'
#cloud-config
# Oxfer relay host (relay.oxfer.app) on Debian 12/13 or Ubuntu 24.04.
# GENERATED by render.sh from the files next to it; do not edit.
#
# Paste this whole file into the provider's "user data" / "cloud-init" field
# when creating the server, and select your SSH key in the provider's panel.
# Create the DNS records first (README.md, "DNS").
#
# First boot writes the kit to /opt/oxfer-relay/ and runs setup.sh, which
# installs the pinned, checksum-verified iroh-relay binary, the systemd unit,
# the firewall and ban tool, log retention, key-only SSH and unattended
# upgrades. Without DNS pointing here it leaves the relay stopped.
# Each file below is the kit file of the same name in
# p2p-transfer/deploy/relay/, gzip-compressed and base64-encoded to fit the
# providers' user-data limits; "sh render.sh --check" proves they match.
# Progress: tail -f /var/log/cloud-init-output.log

ssh_pwauth: false
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - iproute2
  - logrotate
  - nftables
  - unattended-upgrades

write_files:
EOF
	printf '%s\n' "$FILES" | while IFS=: read -r src dst mode; do
		printf '  - path: %s\n    owner: root:root\n    permissions: "%s"\n    encoding: gz+b64\n    content: |\n' "$dst" "$mode"
		{
			gzip -9 -n -c "$src" | base64 | tr -d '\n' | fold -w 76
			echo
		} | sed 's/^/      /'
	done
	cat <<'EOF'

runcmd:
  - [sh, /opt/oxfer-relay/setup.sh]
EOF
}

# split YAML DIR: writes the Nth embedded payload to DIR/N and prints the
# file with the payload lines left out.
split() {
	awk -v dir="$2" '
		/^    content: \|$/ { n++; body = 1; print; next }
		body && /^      / { print substr($0, 7) > (dir "/" n); next }
		{ body = 0; print }
	' "$1"
}

if [ "${1:-}" = "--check" ]; then
	stale=0
	tmp=$(mktemp -d)
	trap 'rm -rf "$tmp"' EXIT
	mkdir "$tmp/have" "$tmp/want"
	render_cloud_init >"$tmp/want.yaml"
	if [ ! -f cloud-init.yaml ] ||
		[ "$(split cloud-init.yaml "$tmp/have")" != "$(split "$tmp/want.yaml" "$tmp/want")" ] ||
		! printf '%s\n' "$FILES" | {
			n=0
			while IFS=: read -r src _; do
				n=$((n + 1))
				base64 -d <"$tmp/have/$n" 2>/dev/null | gzip -dc 2>/dev/null | cmp -s - "$src" || exit 1
			done
		}; then
		echo "cloud-init.yaml is stale" >&2
		stale=1
	fi
	cmp -s config.toml fly/config.toml || { echo "fly/config.toml is stale" >&2; stale=1; }
	unit_log=$(sed -n 's/^Environment="RUST_LOG=\(.*\)"$/\1/p' iroh-relay.service)
	fly_log=$(sed -n 's/^export RUST_LOG="\${RUST_LOG:-\(.*\)}"$/\1/p' fly/entrypoint.sh)
	if [ -z "$unit_log" ] || [ "$unit_log" != "$fly_log" ]; then
		echo "fly/entrypoint.sh's RUST_LOG default differs from iroh-relay.service's; keep them equal by hand" >&2
		exit 1
	fi
	if [ "$stale" -ne 0 ]; then
		echo "run: sh render.sh" >&2
		exit 1
	fi
	echo "cloud-init.yaml and fly/config.toml are up to date"
else
	render_cloud_init >cloud-init.yaml
	cp config.toml fly/config.toml
	echo "wrote cloud-init.yaml ($(wc -c <cloud-init.yaml) bytes) and fly/config.toml"
fi
