#!/bin/sh
# Regenerate the derived files of the relay kit from their sources:
#   cloud-init.yaml   embeds verbatim copies of setup.sh and the host files
#   fly/config.toml   copy of config.toml; the Fly build context is fly/ only
# Usage:
#   sh render.sh           rewrite both files
#   sh render.sh --check   exit 1 if either is stale
# Edit the sources and re-render; never edit the derived files by hand.
set -eu
cd "$(dirname -- "$0")"

# kit file : destination on the host : mode
FILES='setup.sh:/opt/oxfer-relay/setup.sh:0755
config.toml:/opt/oxfer-relay/config.toml:0644
iroh-relay.service:/opt/oxfer-relay/iroh-relay.service:0644
nftables.conf:/opt/oxfer-relay/nftables.conf:0644
journald-oxfer-relay.conf:/opt/oxfer-relay/journald-oxfer-relay.conf:0644
sshd-oxfer-relay.conf:/opt/oxfer-relay/sshd-oxfer-relay.conf:0644
unattended-upgrades.conf:/opt/oxfer-relay/unattended-upgrades.conf:0644'

render_cloud_init() {
	cat <<'EOF'
#cloud-config
# Oxfer relay host (relay.oxfer.app) on Debian 12/13 or Ubuntu 24.04.
# GENERATED by render.sh from the files next to it; do not edit.
#
# Paste this whole file into the provider's "user data" / "cloud-init" field
# when creating the server, and select your SSH key in the provider's panel.
# Create the DNS records first (README.md, "DNS").
#
# First boot writes the kit to /opt/oxfer-relay/ and runs setup.sh, which
# installs the pinned, checksum-verified iroh-relay binary, the systemd unit,
# the firewall, journald retention, key-only SSH and unattended upgrades.
# Progress: tail -f /var/log/cloud-init-output.log

ssh_pwauth: false
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - nftables
  - unattended-upgrades

write_files:
EOF
	printf '%s\n' "$FILES" | while IFS=: read -r src dst mode; do
		printf '  - path: %s\n    owner: root:root\n    permissions: "%s"\n    content: |\n' "$dst" "$mode"
		sed 's/^\(.\)/      \1/' "$src"
	done
	cat <<'EOF'

runcmd:
  - [sh, /opt/oxfer-relay/setup.sh]
EOF
}

if [ "${1:-}" = "--check" ]; then
	stale=0
	render_cloud_init | cmp -s - cloud-init.yaml || { echo "cloud-init.yaml is stale" >&2; stale=1; }
	cmp -s config.toml fly/config.toml || { echo "fly/config.toml is stale" >&2; stale=1; }
	if [ "$stale" -ne 0 ]; then
		echo "run: sh render.sh" >&2
		exit 1
	fi
	echo "cloud-init.yaml and fly/config.toml are up to date"
else
	render_cloud_init > cloud-init.yaml
	cp config.toml fly/config.toml
	echo "wrote cloud-init.yaml ($(wc -c < cloud-init.yaml) bytes) and fly/config.toml"
fi
