#!/bin/sh
# Regenerate cloud-init.yaml, the relay kit's one derived file. It embeds
# setup.sh and the host files, each gzip-compressed and base64-encoded
# (cloud-init "encoding: gz+b64"): as plain text the kit exceeds Hetzner's
# 32 KiB user data. The Fly image builds from the kit files themselves.
# Usage:
#   sh render.sh           rewrite cloud-init.yaml
#   sh render.sh --check   exit 1 if it is stale. It decodes every embedded
#                          file and compares it with its source, so another
#                          gzip build does not count as drift.
# Both fail if setup.sh's KIT_FILES and FILES below name different files.
# Edit the sources and re-render; never edit cloud-init.yaml by hand.
set -eu
cd "$(dirname -- "$0")"

# kit file : mode. Each lands in /opt/oxfer-relay/ under its own name.
# nftables.conf is 0755 there and in /etc, as the nftables package ships it.
FILES='setup.sh:0755
denylist.sh:0755
config.toml:0644
relay.env:0644
iroh-relay.service:0644
nftables.conf:0755
journald-oxfer-relay.conf:0644
sshd-oxfer-relay.conf:0644
unattended-upgrades.conf:0644
logrotate-oxfer-relay.conf:0644
tmpfiles-oxfer-relay.conf:0644
oxfer-relay-ban:0755
oxfer-relay-ban.service:0644
oxfer-relay-ban.timer:0644'

# setup.sh refuses to start unless every file in its KIT_FILES is present.
have=$(sed -n "/^KIT_FILES='/,/'\$/p" setup.sh | sed "s/^KIT_FILES=//; s/'//g" | tr -s '[:space:]' '\n' | grep . | sort)
want=$(printf '%s\n' "$FILES" | cut -d: -f1 | grep -vx setup.sh | sort)
if [ -z "$have" ] || [ "$have" != "$want" ]; then
	echo "setup.sh's KIT_FILES and FILES in render.sh name different files; keep them equal" >&2
	exit 1
fi

render_cloud_init() {
	cat <<'EOF'
#cloud-config
# Oxfer relay host (relay.oxfer.app) on Debian 12/13 or Ubuntu 24.04.
# GENERATED by render.sh from the files next to it; do not edit.
#
# Paste this whole file into the provider's "user data" / "cloud-init" field
# when creating the server, and select your SSH key in the provider's panel.
# Create the DNS records first (README.md, "DNS").
#
# First boot writes the kit to /opt/oxfer-relay/ and runs setup.sh, which
# installs the packages it needs, the pinned, checksum-verified iroh-relay
# binary, the systemd unit, the firewall and ban tool, log retention,
# key-only SSH and unattended upgrades. Without DNS pointing here it leaves
# the relay stopped.
# Each file below is the kit file of the same name in
# p2p-transfer/deploy/relay/, gzip-compressed and base64-encoded to fit the
# providers' user-data limits; "sh render.sh --check" proves they match.
# Progress: tail -f /var/log/cloud-init-output.log

ssh_pwauth: false
package_update: true
package_upgrade: true

write_files:
EOF
	printf '%s\n' "$FILES" | while IFS=: read -r src mode; do
		printf '  - path: /opt/oxfer-relay/%s\n    owner: root:root\n    permissions: "%s"\n    encoding: gz+b64\n    content: |\n' "$src" "$mode"
		{
			gzip -9 -n -c "$src" | base64 | tr -d '\n' | fold -w 76
			echo
		} | sed 's/^/      /'
	done
	cat <<'EOF'

runcmd:
  - [sh, /opt/oxfer-relay/setup.sh]
EOF
}

# split YAML DIR: writes the Nth embedded payload to DIR/N and prints the
# file with the payload lines left out.
split() {
	awk -v dir="$2" '
		/^    content: \|$/ { n++; body = 1; print; next }
		body && /^      / { print substr($0, 7) > (dir "/" n); next }
		{ body = 0; print }
	' "$1"
}

if [ "${1:-}" = "--check" ]; then
	tmp=$(mktemp -d)
	trap 'rm -rf "$tmp"' EXIT
	mkdir "$tmp/have" "$tmp/want"
	render_cloud_init >"$tmp/want.yaml"
	if [ ! -f cloud-init.yaml ] ||
		[ "$(split cloud-init.yaml "$tmp/have")" != "$(split "$tmp/want.yaml" "$tmp/want")" ] ||
		! printf '%s\n' "$FILES" | {
			n=0
			while IFS=: read -r src _; do
				n=$((n + 1))
				base64 -d <"$tmp/have/$n" 2>/dev/null | gzip -dc 2>/dev/null | cmp -s - "$src" || exit 1
			done
		}; then
		echo "cloud-init.yaml is stale; run: sh render.sh" >&2
		exit 1
	fi
	echo "cloud-init.yaml is up to date"
else
	render_cloud_init >cloud-init.yaml
	echo "wrote cloud-init.yaml ($(wc -c <cloud-init.yaml) bytes)"
fi
